# Generated by Django 4.2 on 2023-04-25 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentModel",
            fields=[
                (
                    "uid",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                ("nodes", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="IndexModel",
            fields=[
                (
                    "uid",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                ("index", models.JSONField()),
            ],
        ),
    ]
