# Generated by Django 4.2 on 2023-04-25 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name='document',
    #         name='collection',
    #         field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main.collection'),
    #     ),
    # ]
