# Generated by Django 4.2 on 2023-04-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_document_collection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentmodel",
            name="nodes",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="indexmodel",
            name="index",
            field=models.TextField(),
        ),
    ]
