# Generated by Django 4.2 on 2023-04-27 13:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_documentmodel_nodes_alter_indexmodel_index"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="IndexModel",
            new_name="CollectionModel",
        ),
    ]
