name: learn-with-gpt
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - pip
  - django=4.2
  - bs4=4.12.0
  - pytorch=1.9.1
  - torchvision=0.10.1
  - pywin32
  - poppler
  - libmagic
  - numpy
  - pip:
      - langchain==0.0.146
      - llama-index==0.5.4
      - nltk
      - huggingface-hub
      - layoutparser
      - black
